### ISSUE TITLE
QR Code Generator in JS

### ISSUE THREAD

**Issue by subhasis003** [lovishprabhakar/CSCentral-Hacktoberfest#129]
I will be creating an website which will have the feature of QR code generation for different links, texts and many more.

**Comment by lovishprabhakar** [comment]
@subhasis003 there is already a QR code generator present on the website. If you have any improvements, you are welcome to make them on the already present website, no need to create a new one.

**Comment by lovishprabhakar** [comment]
@subhasis003 status update?

**Comment by swarupsahu08** [comment]
I have created a qr  code generator website and it is in my github profile you can check it out and here is the link to access it:
https://github.com/swarupsahu08/QR-code-generator

**Comment by lovishprabhakar** [comment]
@swarupsahu08 your own website will not count as a contribution to this project. If you want to make a Hacktoberfest Contribution, you will have to add new features to the QR code generator that is present on this website. Then you can make a PR and your contribution will be counted.

**Comment by swarupsahu08** [comment]
ok let me see how I can add value to it

**Comment by swarupsahu08** [comment]
@lovishprabhakar Can I add the size feature for the qrcode for different screen sizes( It means the resolution of qrcode would based on user's preference and there would be options to change the length and breadth of the qrcode.

**Comment by lovishprabhakar** [comment]
Go for it @swarupsahu08

**Comment by swarupsahu08** [comment]
@lovishprabhakar thanks

**Comment by swarupsahu08** [comment]
@lovishprabhakar I have put the pull request ,waiting for the approval for merge
