### ISSUE TITLE
[Bug] Footer having multiple Github logo

### ISSUE THREAD

**Issue by sree-hari-s** [lovishprabhakar/CSCentral-Hacktoberfest#133]
![image](https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/assets/48482060/f2807e68-e34b-4d62-ae0f-e20aa905217e)
 
?

**Comment by lovishprabhakar** [comment]
Go for it @sree-hari-s!

**Comment by sree-hari-s** [comment]
I dont see this issue in the local development

**Comment by lovishprabhakar** [comment]
@sree-hari-s it is a deployment issue then, I will see about fixing it, for now I am closing this issue
