### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by Jai-Marothiya** [lovishprabhakar/CSCentral-Hacktoberfest#135]
In the footer section of the Home page, the GitHub icon is shown multiple times.

**Comment by Jai-Marothiya** [comment]
Hi @lovishprabhakar, 

Kindly assign this issue to me.

Thanks

**Comment by lovishprabhakar** [comment]
Go for it @Jai-Marothiya!

**Comment by Jai-Marothiya** [comment]
Hi @lovishprabhakar,
I created the pull request, kindly merge it with the "Hacktoberfest merge" label.

Thanks
