### ISSUE TITLE
[Tests] Playwright API/E2E Test solution setup

### ISSUE THREAD

**Issue by bugITwhisperer** [lovishprabhakar/CSCentral-Hacktoberfest#136]
### Playwright Tests solution
Would you be interested in having Playwright Test solution with some basic API/E2E tests added to your project? :)

**Comment by bugITwhisperer** [comment]
Thank you Bot. 👍 

/assign

**Comment by bugITwhisperer** [comment]
`/assign`

**Comment by bugITwhisperer** [comment]
Interesting! So `/assign` did not work, neither did a longer comment with /assign in it 😸

**Comment by lovishprabhakar** [comment]
@bugITwhisperer wow, thank you for the analysis of my assign bot, will try to improve it :)
