### ISSUE TITLE
[Bug]: Misplaced github icons in footer.

### ISSUE THREAD

**Issue by purnasth** [lovishprabhakar/CSCentral-Hacktoberfest#140]
# Issue Title: Bug - Misplaced GitHub Icon in Footer

## Issue Description:
I've noticed a bug in the project's footer where the GitHub icon is misplaced and appears unorganized. This issue affects the overall aesthetics and functionality of the project, and it's important to address it for a better user experience.

## Bug Details:
- **Location**: The GitHub icon in the footer.
- **Issue**: Misplaced and unorganized placement.
- **Severity**: Low (Aesthetic issue but affects user experience).

## Steps to Reproduce:
1. Navigate to the project's footer section.
2. Observe the placement of the GitHub icon.

## Screenshots (if applicable):
![image](https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/assets/107195487/07ab6cb7-133d-4894-9905-440f618bd936)

## Additional Information (if available):
Please advise if there are specific guidelines for addressing and resolving this issue or if any additional details are needed. I am committed to helping resolve this bug effectively.

Please prioritize this issue as it negatively impacts the project's appearance and user experience. Thank you for your attention to this matter.

**Comment by lovishprabhakar** [comment]
Go for it, @purnasth!
**Additional Information:** The people who tried to fix this issue earlier have reported that they don't see it on their local servers. The multiple logos appear only after being deployed on GitHub pages. If you can check that, it would be much appreciated.

**Comment by purnasth** [comment]
Alright. I attempted to work on this problem; but, I'm not sure if it's resolved. What I did was. The index.html page is now fully functional in my repository after I relocated it to the web's root folder and hosted it on github Pages. Should I file a PR right away for this?
