### ISSUE TITLE
[Bug]: Remove Scrollbar from Dropdown Menu in Navbar

### ISSUE THREAD

**Issue by purnasth** [lovishprabhakar/CSCentral-Hacktoberfest#142]
# Issue Title: Bug - Remove Scrollbar from Dropdown Menu in Navbar

## Issue Description:
I've identified a bug in the project's navigation bar where a scrollbar appears within the dropdown menu. This issue affects the aesthetics and functionality of the menu, and it's important to remove the scrollbar for a smoother user experience.

## Bug Details:
- **Location**: The dropdown menu in the project's navigation bar.
- **Issue**: Unwanted scrollbar appearance.

## Actual Behavior:
The dropdown menu currently displays a scrollbar, which affects the visual consistency and user experience.

## Screenshots:
![image](https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/assets/107195487/db8e800f-9ec0-466c-b387-00d595c9b08c)

**Comment by lovishprabhakar** [comment]
Yeah we can try and see if that works @purnasth
