### ISSUE TITLE
[BUG] [CER - More calculations] missing success message after conversion

### ISSUE THREAD

**Issue by bugITwhisperer** [lovishprabhakar/CSCentral-Hacktoberfest#152]
**Expected Results**
<img src='https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/assets/97608493/3ad1363e-4426-4785-b128-fd421acdf852' width='450'>

**Actual Results**
In the `Convert with your quantities` modal, after successful conversion (`Convert` button clicked), there is no success success message displayed which makes it a bit inconsistent with the basic conversion tool:
<img src='https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/assets/97608493/18684663-ac18-41fb-aaaa-e8526a48ef9d' width='750'>

**Steps to reproduce**
1. go to CER page: https://lovishprabhakar.is-a.dev/CS-Central/Code/currency-change.html
2. click "Convert" button -> observe inline success message being displayed
3. click "More Calculations?" button
4. type number in the input
5. click "Convert" button -> observe there is no inline success message displayed

**Comment by lovishprabhakar** [comment]
Bug noted @bugITwhisperer, thanks for letting me know. Will you be working on fixing it or shall I close the issue?

**Comment by lovishprabhakar** [comment]
Alright, good luck! @bugITwhisperer

**Comment by lovishprabhakar** [comment]
I'll just pin the issue @bugITwhisperer so the bot won't comment time and again, carry on with the work!

**Comment by bugITwhisperer** [comment]
@bugITwhisperer : thanks a lot!!! 👍🏻

**Comment by bugITwhisperer** [comment]
@lovishprabhakar: totally forgot about this ISSUE, my bad! I've just started working on the fix attempt. Any chance you could re-open it please? I will open a new PR with the fix attempt shortly :)

**Comment by lovishprabhakar** [comment]
Reopened @bugITwhisperer.

**Comment by bugITwhisperer** [comment]
btw. @lovishprabhakar you can unpin the issue now that it's done :)
