### ISSUE TITLE
[Feature Request] set up automated test-run when PR with new code changes gets created

### ISSUE THREAD

**Issue by bugITwhisperer** [lovishprabhakar/CSCentral-Hacktoberfest#161]
##  Automated test-run on Pull Request creation

When a contributor creates a new PR with any code changes, it will automatically trigger a CI (GitHub Actions) job with a test-run. This feature will provide immediate feedback on the proposed changes, ensuring the integrity of the codebase early in the development process :)

**Comment by lovishprabhakar** [comment]
Pinning this one in place of the previous one then @bugITwhisperer ^_^

**Comment by bugITwhisperer** [comment]
Any chance you can stop this run: https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/actions/runs/7034745770/job/19143503892 ? :)

**Comment by lovishprabhakar** [comment]
> Any chance you can cancel these from running: https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/actions/runs/7034656673/job/19143206113 https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/actions/runs/7034745770/job/19143503892 ? :)

Done!
